import { default as React } from '../../../../../node_modules/react';
export type AudioLabels = {
    seek?: string;
    mute?: string;
    unmute?: string;
    volume?: string;
    play?: string;
    pause?: string;
    next?: string;
    prev?: string;
    repeatMode0?: string;
    repeatMode1?: string;
    repeatMode2?: string;
    shuffle?: string;
    playbackSpeed?: string;
    bassBoost?: string;
    sleepTimer?: string;
    unknownTitle?: string;
    unknownArtist?: string;
};
interface AudioCustomControlsProps {
    isPlaying: boolean;
    currentTime: number;
    duration: number;
    volume: number;
    isMuted: boolean;
    repeatMode: 0 | 1 | 2;
    shuffleMode: boolean;
    currentPlaybackRate: number;
    isBassBoost: boolean;
    remainingSleepTime: number | null;
    playbackRate: boolean;
    presets: boolean;
    sleepTimer: boolean;
    setRepeatMode: React.Dispatch<React.SetStateAction<0 | 1 | 2>>;
    setShuffleMode: React.Dispatch<React.SetStateAction<boolean>>;
    setCurrentPlaybackRate: (rate: number) => void;
    setIsBassBoost: (boost: boolean) => void;
    setIsMuted: React.Dispatch<React.SetStateAction<boolean>>;
    togglePlay: () => void;
    handleSeek: (e: React.ChangeEvent<HTMLInputElement>) => void;
    handleVolumeChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    playNext: (dir: 1 | -1) => void;
    toggleSleepTimer: () => void;
    formatTime: (time: number) => string;
    labels?: AudioLabels;
}
export declare function AudioCustomControls({ isPlaying, currentTime, duration, volume, isMuted, repeatMode, shuffleMode, currentPlaybackRate, isBassBoost, remainingSleepTime, playbackRate, presets, sleepTimer, setRepeatMode, setShuffleMode, setCurrentPlaybackRate, setIsBassBoost, setIsMuted, togglePlay, handleSeek, handleVolumeChange, playNext, toggleSleepTimer, formatTime, labels, }: AudioCustomControlsProps): import("react/jsx-runtime").JSX.Element;
export {};
