import StyleDictionary from 'style-dictionary';

const toPascalCase = (str) => {
  return str
    .split(/[-_ ]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
};

StyleDictionary.registerFormat({
  name: 'typescript/union',
  format: ({ dictionary }) => {
    const categories = {};
    
    dictionary.allTokens.forEach(token => {
      // Group tokens by category (the second part of the path: wim.category.token)
      if (token.path[0] === 'wim') {
        const cat = token.path[1];
        if (!categories[cat]) categories[cat] = [];
        
        // Join the rest of the path to form the key
        const key = token.path.slice(2).join('-');
        if (key && !categories[cat].includes(key)) {
          categories[cat].push(key);
        }
      }
    });

    let output = `/**\n * Do not edit directly, this file was auto-generated by Style Dictionary.\n */\n\n`;

    Object.entries(categories).forEach(([cat, keys]) => {
      let typeName = `Wim${toPascalCase(cat)}Key`;
      // Specific mapping for clarity
      if (cat === 'z') typeName = 'WimZIndexKey';
      
      output += `export type ${typeName} = \n  | ${keys.sort().map(k => `"${k}"`).join('\n  | ')};\n\n`;
    });

    return output;
  }
});

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    scss: {
      transformGroup: 'scss',
      buildPath: 'src/tokens/generated/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/variables',
          filter: (token) => token.path[0] === 'wim'
        },
        {
          destination: '_css-vars.scss',
          format: 'css/variables',
          options: {
            selector: ':root'
          },
          filter: (token) => token.path[0] === 'wim'
        }
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'src/types/',
      files: [
        {
          destination: 'generated-tokens.ts',
          format: 'typescript/union',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log('Style Dictionary build complete.');
