export * from './components/Code/Code';
export * from './components/Heading/Heading';
export * from './components/Highlight/Highlight';
export * from './components/Kbd/Kbd';
export * from './components/Label/Label';
export * from './components/Legend/Legend';
export * from './components/Paragraph/Paragraph';
export * from './components/Quote/Quote';
export * from './components/Span/Span';
