import { default as React } from '../../../node_modules/react';
import { SelectboxOption, SelectboxProps } from './Selectbox';
type UseSelectboxParams = Pick<SelectboxProps, "options" | "value" | "onChange" | "defaultValue" | "searchable" | "grouped" | "disabled" | "filterOption">;
export declare function useSelectbox({ options, value, onChange, defaultValue, searchable, grouped, disabled, filterOption, }: UseSelectboxParams): {
    isOpen: boolean;
    searchValue: string;
    setSearchValue: React.Dispatch<React.SetStateAction<string>>;
    focusedIndex: number;
    setFocusedIndex: React.Dispatch<React.SetStateAction<number>>;
    isKeyboardNavigating: boolean;
    setIsKeyboardNavigating: React.Dispatch<React.SetStateAction<boolean>>;
    containerRef: React.RefObject<HTMLDivElement | null>;
    triggerRef: React.RefObject<HTMLDivElement | null>;
    searchInputRef: React.RefObject<HTMLInputElement | null>;
    listItemsRef: React.RefObject<(HTMLElement | null)[]>;
    currentValue: string;
    flatOptions: SelectboxOption[];
    filteredOptions: SelectboxOption[];
    selectedOption: SelectboxOption | undefined;
    focusedOption: SelectboxOption | null;
    handleToggle: () => void;
    handleSelect: (option: SelectboxOption) => void;
    handleClear: () => void;
    handleKeyDown: (e: React.KeyboardEvent) => void;
};
export {};
