import { default as AlertCircleIcon } from './alert-circle.svg?react';
import { default as AlertTriangleIcon } from './alert-triangle.svg?react';
import { default as AlignJustifyIcon } from './align-justify.svg?react';
import { default as ArrowDownIcon } from './arrow-down.svg?react';
import { default as ArrowLeftIcon } from './arrow-left.svg?react';
import { default as ArrowRightIcon } from './arrow-right.svg?react';
import { default as ArrowUpIcon } from './arrow-up.svg?react';
import { default as BellIcon } from './bell.svg?react';
import { default as BoldIcon } from './bold.svg?react';
import { default as CalendarIcon } from './calendar.svg?react';
import { default as ChartIcon } from './chart.svg?react';
import { default as CheckCircleIcon } from './check-circle.svg?react';
import { default as CheckIcon } from './check.svg?react';
import { default as ChevronDownIcon } from './chevron-down.svg?react';
import { default as ChevronLeftIcon } from './chevron-left.svg?react';
import { default as ChevronRightIcon } from './chevron-right.svg?react';
import { default as ChevronUpIcon } from './chevron-up.svg?react';
import { default as CircleIcon } from './circle.svg?react';
import { default as ClockIcon } from './clock.svg?react';
import { default as CloseSmallIcon } from './close-small.svg?react';
import { default as CloseIcon } from './close.svg?react';
import { default as ColumnsIcon } from './columns.svg?react';
import { default as CopyIcon } from './copy.svg?react';
import { default as CreditCardIcon } from './credit-card.svg?react';
import { default as DocumentIcon } from './document.svg?react';
import { default as DownloadIcon } from './download.svg?react';
import { default as EditIcon } from './edit.svg?react';
import { default as EmailIcon } from './email.svg?react';
import { default as EraserIcon } from './eraser.svg?react';
import { default as ExternalLinkIcon } from './external-link.svg?react';
import { default as EyeOffIcon } from './eye-off.svg?react';
import { default as EyeIcon } from './eye.svg?react';
import { default as FilterIcon } from './filter.svg?react';
import { default as GridIcon } from './grid.svg?react';
import { default as GripVerticalIcon } from './grip-vertical.svg?react';
import { default as HelpCircleIcon } from './help-circle.svg?react';
import { default as HomeIcon } from './home.svg?react';
import { default as HourglassIcon } from './hourglass.svg?react';
import { default as ImageIcon } from './image.svg?react';
import { default as InfoCircleIcon } from './info-circle.svg?react';
import { default as ItalicIcon } from './italic.svg?react';
import { default as LinkIcon } from './link.svg?react';
import { default as ListOrderedIcon } from './list-ordered.svg?react';
import { default as ListIcon } from './list.svg?react';
import { default as LoadingIcon } from './loading.svg?react';
import { default as LogInIcon } from './log-in.svg?react';
import { default as LogOutIcon } from './log-out.svg?react';
import { default as MaximizeIcon } from './maximize.svg?react';
import { default as MenuIcon } from './menu.svg?react';
import { default as MinimizeIcon } from './minimize.svg?react';
import { default as MinusIcon } from './minus.svg?react';
import { default as MonitorIcon } from './monitor.svg?react';
import { default as MoonIcon } from './moon.svg?react';
import { default as MoreHorizontalIcon } from './more-horizontal.svg?react';
import { default as MoreVerticalIcon } from './more-vertical.svg?react';
import { default as MuteIcon } from './mute.svg?react';
import { default as PaperclipIcon } from './paperclip.svg?react';
import { default as PauseIcon } from './pause.svg?react';
import { default as PdfIcon } from './pdf.svg?react';
import { default as PhoneIcon } from './phone.svg?react';
import { default as PipIcon } from './pip.svg?react';
import { default as PlayIcon } from './play.svg?react';
import { default as PlusIcon } from './plus.svg?react';
import { default as ProjectIcon } from './project.svg?react';
import { default as RefreshIcon } from './refresh.svg?react';
import { default as RepeatIcon } from './repeat.svg?react';
import { default as SearchIcon } from './search.svg?react';
import { default as SendIcon } from './send.svg?react';
import { default as SettingsIcon } from './settings.svg?react';
import { default as ShareIcon } from './share.svg?react';
import { default as ShuffleIcon } from './shuffle.svg?react';
import { default as SkipBackIcon } from './skip-back.svg?react';
import { default as SkipForwardIcon } from './skip-forward.svg?react';
import { default as SmartphoneIcon } from './smartphone.svg?react';
import { default as SpinnerIcon } from './spinner.svg?react';
import { default as SquareIcon } from './square.svg?react';
import { default as StarIcon } from './star.svg?react';
import { default as StrikethroughIcon } from './strikethrough.svg?react';
import { default as SunIcon } from './sun.svg?react';
import { default as ThumbDownIcon } from './thumb-down.svg?react';
import { default as ThumbUpIcon } from './thumb-up.svg?react';
import { default as TrashIcon } from './trash.svg?react';
import { default as UnderlineIcon } from './underline.svg?react';
import { default as UnlinkIcon } from './unlink.svg?react';
import { default as UploadIcon } from './upload.svg?react';
import { default as UserIcon } from './user.svg?react';
import { default as VideoIcon } from './video.svg?react';
import { default as VolumeIcon } from './volume.svg?react';
export { AlertCircleIcon, AlertTriangleIcon, AlignJustifyIcon, ArrowDownIcon, ArrowLeftIcon, ArrowRightIcon, ArrowUpIcon, BellIcon, BoldIcon, CalendarIcon, ChartIcon, CheckCircleIcon, CheckIcon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, ChevronUpIcon, CircleIcon, ClockIcon, CloseSmallIcon, CloseIcon, ColumnsIcon, CopyIcon, CreditCardIcon, DocumentIcon, DownloadIcon, EditIcon, EmailIcon, EraserIcon, ExternalLinkIcon, EyeOffIcon, EyeIcon, FilterIcon, GridIcon, GripVerticalIcon, HelpCircleIcon, HomeIcon, HourglassIcon, ImageIcon, InfoCircleIcon, ItalicIcon, LinkIcon, ListOrderedIcon, ListIcon, LoadingIcon, LogInIcon, LogOutIcon, MaximizeIcon, MenuIcon, MinimizeIcon, MinusIcon, MonitorIcon, MoonIcon, MoreHorizontalIcon, MoreVerticalIcon, MuteIcon, PaperclipIcon, PauseIcon, PdfIcon, PhoneIcon, PipIcon, PlayIcon, PlusIcon, ProjectIcon, RefreshIcon, RepeatIcon, SearchIcon, SendIcon, SettingsIcon, ShareIcon, ShuffleIcon, SkipBackIcon, SkipForwardIcon, SmartphoneIcon, SpinnerIcon, SquareIcon, StarIcon, StrikethroughIcon, SunIcon, ThumbDownIcon, ThumbUpIcon, TrashIcon, UnderlineIcon, UnlinkIcon, UploadIcon, UserIcon, VideoIcon, VolumeIcon, };
export declare const ALL_ICONS: {
    readonly AlertCircleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly AlertTriangleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly AlignJustifyIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ArrowDownIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ArrowLeftIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ArrowRightIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ArrowUpIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly BellIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly BoldIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CalendarIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ChartIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CheckCircleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CheckIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ChevronDownIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ChevronLeftIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ChevronRightIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ChevronUpIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CircleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ClockIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CloseSmallIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CloseIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ColumnsIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CopyIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly CreditCardIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly DocumentIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly DownloadIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly EditIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly EmailIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly EraserIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ExternalLinkIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly EyeOffIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly EyeIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly FilterIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly GridIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly GripVerticalIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly HelpCircleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly HomeIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly HourglassIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ImageIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly InfoCircleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ItalicIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly LinkIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ListOrderedIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ListIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly LoadingIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly LogInIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly LogOutIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MaximizeIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MenuIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MinimizeIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MinusIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MonitorIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MoonIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MoreHorizontalIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MoreVerticalIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly MuteIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PaperclipIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PauseIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PdfIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PhoneIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PipIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PlayIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly PlusIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ProjectIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly RefreshIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly RepeatIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SearchIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SendIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SettingsIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ShareIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ShuffleIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SkipBackIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SkipForwardIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SmartphoneIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SpinnerIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SquareIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly StarIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly StrikethroughIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly SunIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ThumbDownIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly ThumbUpIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly TrashIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly UnderlineIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly UnlinkIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly UploadIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly UserIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly VideoIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
    readonly VolumeIcon: import('../../node_modules/react').FC<import('../../node_modules/react').SVGProps<SVGSVGElement>>;
};
export type IconName = keyof typeof ALL_ICONS;
