/**
 * Do not edit directly, this file was auto-generated by Style Dictionary.
 */

export type WimColorKey = 
  | "avatar-default"
  | "avatar-s1"
  | "avatar-s10"
  | "avatar-s12"
  | "avatar-s14"
  | "avatar-s16"
  | "avatar-s18"
  | "avatar-s20"
  | "avatar-s22"
  | "avatar-s24"
  | "avatar-s3"
  | "avatar-s5"
  | "avatar-s7"
  | "border"
  | "border-inverse"
  | "border-secondary"
  | "carousel-control-bg"
  | "carousel-control-hover-bg"
  | "carousel-indicator-bg"
  | "carousel-indicator-hover-bg"
  | "chart-1"
  | "chart-2"
  | "chart-3"
  | "chart-4"
  | "chart-5"
  | "chart-6"
  | "chart-7"
  | "chart-8"
  | "chat-bubble-received"
  | "chat-bubble-sent"
  | "close-hover"
  | "control-default-bg"
  | "control-default-border"
  | "control-default-fg"
  | "danger"
  | "danger-subtle"
  | "decoration-highlight-color"
  | "disabled"
  | "feedback-bg-base"
  | "feedback-border-strength"
  | "feedback-text-base"
  | "focus-outline"
  | "frosted-bg"
  | "ghost-bg"
  | "ghost-bg-active"
  | "ghost-bg-hover"
  | "ghost-border"
  | "ghost-border-active"
  | "ghost-border-hover"
  | "glass-bg"
  | "glass-blur"
  | "glass-blur-lg"
  | "glass-blur-sm"
  | "glass-border"
  | "heatmap-level-0"
  | "heatmap-level-1"
  | "heatmap-level-2"
  | "heatmap-level-3"
  | "heatmap-level-4"
  | "info"
  | "overlay"
  | "overlay-control-active"
  | "overlay-control-hover"
  | "overlay-control-track"
  | "overlay-divider"
  | "overlay-item-hover"
  | "overlay-medium"
  | "overlay-menu-bg"
  | "overlay-sidebar"
  | "overlay-soft"
  | "overlay-strong"
  | "primary"
  | "primary-active"
  | "primary-fill"
  | "primary-hover"
  | "primary-muted"
  | "primary-rgb"
  | "primary-soft"
  | "primary-subtle"
  | "scrollbar-thumb"
  | "scrollbar-track"
  | "secondary"
  | "shadow-glass"
  | "skeleton-bg"
  | "skeleton-shine"
  | "success"
  | "surface"
  | "surface-app"
  | "surface-hover"
  | "surface-inset"
  | "surface-inverse"
  | "surface-subtle"
  | "surface-subtle-alpha"
  | "surface-tertiary"
  | "surface-variant"
  | "surface-variant-alpha"
  | "surface-void"
  | "terminal-traffic-green"
  | "terminal-traffic-red"
  | "terminal-traffic-yellow"
  | "text-accent"
  | "text-danger"
  | "text-disabled"
  | "text-muted-on-inverse"
  | "text-on-danger"
  | "text-on-disabled"
  | "text-on-info"
  | "text-on-inverse"
  | "text-on-overlay"
  | "text-on-primary"
  | "text-on-secondary"
  | "text-on-success"
  | "text-on-warning"
  | "text-placeholder"
  | "text-primary"
  | "text-secondary"
  | "text-tertiary"
  | "warning"
  | "white";

export type WimBreakpointKey = 
  | "lg"
  | "md"
  | "sm"
  | "xl"
  | "xs";

export type WimZIndexKey = 
  | "drawer"
  | "header"
  | "mask"
  | "navbar"
  | "overlay"
  | "overlay-panel"
  | "overlay-step"
  | "sidebar"
  | "sticky"
  | "toast";

export type WimOpacityKey = 
  | "dim"
  | "disabled"
  | "ghost"
  | "secondary"
  | "subtle";

export type WimBlurKey = 
  | "2xl"
  | "2xs"
  | "glass"
  | "lg"
  | "md"
  | "none"
  | "overlay"
  | "sm"
  | "xl"
  | "xs";

export type WimGlassKey = 
  | "bg-opacity"
  | "bg-opacity-dark"
  | "border-opacity"
  | "border-opacity-dark";

export type WimShadowKey = 
  | "error-ring"
  | "field-focus"
  | "focus"
  | "focus-ring"
  | "inset"
  | "lg"
  | "md"
  | "modal"
  | "none"
  | "overlay"
  | "sm"
  | "xs";

export type WimDurationKey = 
  | "base"
  | "breathe"
  | "circle"
  | "extra-fast"
  | "extra-slow"
  | "fast"
  | "slow"
  | "slowest"
  | "ultra-fast"
  | "ultra-slow";

export type WimEasingKey = 
  | "emphasized"
  | "emphasized-accelerate"
  | "emphasized-decelerate"
  | "entrance"
  | "exit"
  | "gentle"
  | "out-back"
  | "sharp"
  | "snap"
  | "spring"
  | "standard";

export type WimTransitionKey = 
  | "base"
  | "fast"
  | "slow"
  | "spring";

export type WimLiftKey = 
  | "lg"
  | "md"
  | "none"
  | "sm";

export type WimScaleKey = 
  | "active"
  | "hover";

export type WimSpacingKey = 
  | "2xl"
  | "2xs"
  | "3xl"
  | "3xs"
  | "4xl"
  | "5xl"
  | "hairline"
  | "lg"
  | "md"
  | "sm"
  | "xl"
  | "xs";

export type WimRadiusKey = 
  | "2xl"
  | "component"
  | "container"
  | "full"
  | "lg"
  | "md"
  | "overlay"
  | "sm"
  | "xl";

export type WimBorderWidthKey = 
  | "thick"
  | "thin";

export type WimFocusOutlineKey = 
  | "offset"
  | "width";

export type WimFontFamilyKey = 
  | "default"
  | "en"
  | "ja"
  | "mono"
  | "pt";

export type WimFontSizeKey = 
  | "2xl"
  | "2xs"
  | "3xl"
  | "3xs"
  | "4xl"
  | "5xl"
  | "6xl"
  | "7xl"
  | "lg"
  | "md"
  | "sm"
  | "xl"
  | "xs";

export type WimFontWeightKey = 
  | "bold"
  | "medium"
  | "normal"
  | "semibold";

export type WimLineHeightKey = 
  | "loose"
  | "loose-jp"
  | "normal"
  | "normal-jp"
  | "snug"
  | "snug-jp"
  | "tight"
  | "tight-jp";

export type WimDecorationKey = 
  | "line-through"
  | "underline";

