/**
 * Do not edit directly, this file was auto-generated by Style Dictionary.
 */

export type WimPaletteKey = 
  | "caution"
  | "destructive"
  | "disabled"
  | "focus-outline"
  | "informative"
  | "positive"
  | "primary"
  | "secondary"
  | "text-on-caution"
  | "text-on-destructive"
  | "text-on-disabled"
  | "text-on-informative"
  | "text-on-positive"
  | "text-on-primary"
  | "text-on-secondary";

export type WimTextBaseKey = 
  | "black"
  | "deepgray"
  | "error"
  | "gray"
  | "lightgray"
  | "white";

export type WimScrollbarBaseKey = 
  | "thumb"
  | "track";

export type WimColorKey = 
  | "bg-app"
  | "bg-component"
  | "bg-hover"
  | "bg-primary"
  | "bg-secondary"
  | "border"
  | "border-secondary"
  | "caution"
  | "destructive"
  | "disabled"
  | "focus-outline"
  | "informative"
  | "positive"
  | "primary"
  | "primary-active"
  | "primary-hover"
  | "primary-light"
  | "scrollbar-thumb"
  | "scrollbar-track"
  | "secondary"
  | "surface"
  | "surface-hover"
  | "surface-variant"
  | "text-disabled"
  | "text-error"
  | "text-on-caution"
  | "text-on-destructive"
  | "text-on-disabled"
  | "text-on-informative"
  | "text-on-positive"
  | "text-on-primary"
  | "text-on-secondary"
  | "text-placeholder"
  | "text-primary"
  | "text-secondary"
  | "text-tertiary"
  | "text-white";

export type WimZIndexKey = 
  | "overlay"
  | "overlay-panel"
  | "overlay-step"
  | "sidebar"
  | "toast";

export type WimOpacityKey = 
  | "disabled"
  | "ghost"
  | "secondary";

export type WimShadowKey = 
  | "field-focus"
  | "focus"
  | "inset"
  | "lg"
  | "md"
  | "none"
  | "sm"
  | "xs";

export type WimSpacingKey = 
  | "2xl"
  | "2xs"
  | "3xl"
  | "3xs"
  | "4xl"
  | "5xl"
  | "lg"
  | "md"
  | "sm"
  | "xl"
  | "xs";

export type WimRadiusKey = 
  | "full"
  | "lg"
  | "md"
  | "sm"
  | "xl";

