#!/usr/bin/env node
// Generate theme presets ("brand kits") from tokens/presets/*.json.
//
// A preset is a small set of role-token overrides that switch a screen's
// "feel" (shape + accent) in one attribute. It layers on top of styles.css
// and composes with light/dark and density — nothing here is a new base token.
//
// Emits (both generated, do not edit by hand):
//   - src/tokens/generated/_presets.scss  … [data-wim-preset="…"] { --wim-* }
//   - src/tokens/generated/presets.ts     … WIM_PRESETS + WimPresetName type
//
// Accent colors are referenced from the PCCS palette (tokens/color/base.json)
// as {pccs.xxx}, so presets stay single-sourced with the rest of the tokens.
// When a preset sets an accent it also writes --wim-color-primary-rgb (derived
// components read the rgb form); primary-hover/active auto-derive via
// `oklch(from var(--wim-color-primary) …)` and need no override.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const readJSON = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));

const pccs = readJSON('tokens/color/base.json').pccs;

// Resolve a value that may be a `{pccs.key}` reference into a literal hex.
const resolve = (v) => {
  const m = typeof v === 'string' && v.match(/^\{pccs\.([\w-]+)\}$/);
  if (!m) return v;
  const entry = pccs[m[1]];
  const hex = entry && (entry.value ?? entry);
  if (!hex) throw new Error(`generate-presets: unknown pccs ref "${v}"`);
  return hex;
};

// "#205b85" -> "32, 91, 133"
const toRgb = (hex) => {
  let h = String(hex).replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const n = parseInt(h, 16);
  return `${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}`;
};

const presetsDir = join(ROOT, 'tokens/presets');
const presets = readdirSync(presetsDir)
  .filter((f) => f.endsWith('.json'))
  .map((f) => ({ name: f.replace(/\.json$/, ''), ...readJSON(`tokens/presets/${f}`) }))
  .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

// --- _presets.scss ---------------------------------------------------------

const decls = (pairs, indent = '  ') =>
  pairs.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

const radiusDecls = (radius) =>
  Object.entries(radius ?? {}).map(([k, v]) => [`--wim-radius-${k}`, v]);

// A single accent value that works in both light and dark: `--wim-color-primary`
// drives fills (button backgrounds, emphasis; white text stays AA), and links
// derive from it via color-mix. hover/active + primary-rgb-based tints auto-follow.
// Accents are chosen (see scripts/verify — PCCS mid-tones) to keep both the
// white-on-fill and the mixed link text AA in either theme, so no per-theme split
// or text-accent override is needed.
const accentDecls = (accent) => {
  if (!accent) return [];
  const hex = resolve(accent);
  return [
    ['--wim-color-primary', hex],
    ['--wim-color-primary-rgb', toRgb(hex)],
  ];
};

let scss = `/**\n * Do not edit directly — generated by scripts/generate-presets.js.\n * Theme presets: [data-wim-preset="…"] role-token overrides (radius + accent).\n * A preset applies in any theme and can scope to any subtree.\n */\n`;

for (const p of presets) {
  const block = [...radiusDecls(p.radius), ...accentDecls(p.accent)];
  scss += `\n[data-wim-preset="${p.name}"] {\n${decls(block)}\n}\n`;
}

writeFileSync(join(ROOT, 'src/tokens/generated/_presets.scss'), scss);

// --- presets.ts ------------------------------------------------------------

const entries = presets
  .map(
    (p) =>
      `  { name: "${p.name}", label: ${JSON.stringify(p.label)}, description: ${JSON.stringify(
        p.description,
      )} },`,
  )
  .join('\n');

const ts = `/**
 * Do not edit directly — generated by scripts/generate-presets.js.
 * Public catalog of theme presets. Consumed by WimProvider / docs.
 */

export const WIM_PRESETS = [
${entries}
] as const;

/** Name of a built-in theme preset. */
export type WimPresetName = (typeof WIM_PRESETS)[number]["name"];
`;

writeFileSync(join(ROOT, 'src/tokens/generated/presets.ts'), ts);

console.log(`✓ generated ${presets.length} presets: ${presets.map((p) => p.name).join(', ')}`);
